// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
bool _OpMode;

[numthreads(16,16,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{

    if (_OpMode) {
        Result[id.xy] = float4(Result[id.xy].xyz, 0.0);
    }
    else {
        Result[id.xy] = float4(0.0, 0.0, 0.0, Result[id.xy].w);
    }
    
}
